# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regen_log_SE',
            fields=[
                ('nvertx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('regen_log_se_UC', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_0HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_2HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_4HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_8HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_12HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_16HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_20HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_24HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_36HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_48HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_60HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_72HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_96HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_120HPA', models.FloatField(blank=True, max_length=10, null=True)),
                ('regen_log_se_144HPA', models.FloatField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_0HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_120HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_12HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_144HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_16HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_20HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_24HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_2HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_36HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_48HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_4HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_60HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_72HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_8HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_96HPA',
        ),
        migrations.RemoveField(
            model_name='regen_se',
            name='regen_log_se_UC',
        ),
    ]
