# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0002_auto_20170621_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfuzz',
            name='mfuzz_cluster_nb',
            field=models.CharField(max_length=4),
        ),
    ]
