# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0004_auto_20170308_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cpm',
            new_name='Regen_cpm',
        ),
    ]
