# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0005_auto_20170308_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('nvertx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nve_hit', models.CharField(max_length=30)),
                ('nve_eval', models.FloatField(max_length=10)),
                ('mfuzz_clust', models.IntegerField(max_length=2)),
                ('mfuzz_score', models.FloatField(max_length=10)),
                ('uniprot_id', models.CharField(max_length=10)),
                ('uniprot_description', models.CharField(max_length=100)),
                ('top_nr_hit_eval', models.CharField(max_length=1000)),
                ('other_nr_hits', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Embryo_cpm',
            fields=[
                ('nvertx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('warner_anc_24HPF', models.FloatField(max_length=10)),
                ('warner_anc_48HPF', models.FloatField(max_length=10)),
                ('warner_anc_72HPF', models.FloatField(max_length=10)),
                ('warner_anc_96HPF', models.FloatField(max_length=10)),
                ('warner_anc_120HPF', models.FloatField(max_length=10)),
                ('warner_anc_144HPF', models.FloatField(max_length=10)),
                ('warner_anc_168HPF', models.FloatField(max_length=10)),
                ('warner_anc_192HPF', models.FloatField(max_length=10)),
                ('fischer_anc_0HPF', models.FloatField(max_length=10)),
                ('fischer_anc_1HPF', models.FloatField(max_length=10)),
                ('fischer_anc_2HPF', models.FloatField(max_length=10)),
                ('fischer_anc_3HPF', models.FloatField(max_length=10)),
                ('fischer_anc_4HPF', models.FloatField(max_length=10)),
                ('fischer_anc_5HPF', models.FloatField(max_length=10)),
                ('fischer_anc_6HPF', models.FloatField(max_length=10)),
                ('fischer_anc_7HPF', models.FloatField(max_length=10)),
                ('fischer_anc_8HPF', models.FloatField(max_length=10)),
                ('fischer_anc_9HPF', models.FloatField(max_length=10)),
                ('fischer_anc_10HPF', models.FloatField(max_length=10)),
                ('fischer_anc_11HPF', models.FloatField(max_length=10)),
                ('fischer_anc_12HPF', models.FloatField(max_length=10)),
                ('fischer_anc_13HPF', models.FloatField(max_length=10)),
                ('fischer_anc_14HPF', models.FloatField(max_length=10)),
                ('fischer_anc_15HPF', models.FloatField(max_length=10)),
                ('fischer_anc_16HPF', models.FloatField(max_length=10)),
                ('fischer_anc_17HPF', models.FloatField(max_length=10)),
                ('fischer_anc_18HPF', models.FloatField(max_length=10)),
                ('fischer_anc_19HPF', models.FloatField(max_length=10)),
                ('helm_anc_2HPF', models.FloatField(max_length=10)),
                ('helm_anc_7HPF', models.FloatField(max_length=10)),
                ('helm_anc_12HPF', models.FloatField(max_length=10)),
                ('helm_anc_24HPF', models.FloatField(max_length=10)),
                ('helm_anc_120HPF', models.FloatField(max_length=10)),
                ('helm_anc_240HPF', models.FloatField(max_length=10)),
            ],
        ),
    ]
