# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0007_auto_20170308_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_Error',
            fields=[
                ('nvertx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('regen_se_UC', models.FloatField(max_length=10)),
                ('regen_se_0HPA', models.FloatField(max_length=10)),
                ('regen_se_2HPA', models.FloatField(max_length=10)),
                ('regen_se_4HPA', models.FloatField(max_length=10)),
                ('regen_se_8HPA', models.FloatField(max_length=10)),
                ('regen_se_12HPA', models.FloatField(max_length=10)),
                ('regen_se_16HPA', models.FloatField(max_length=10)),
                ('regen_se_20HPA', models.FloatField(max_length=10)),
                ('regen_se_24HPA', models.FloatField(max_length=10)),
                ('regen_se_36HPA', models.FloatField(max_length=10)),
                ('regen_se_48HPA', models.FloatField(max_length=10)),
                ('regen_se_60HPA', models.FloatField(max_length=10)),
                ('regen_se_72HPA', models.FloatField(max_length=10)),
                ('regen_se_96HPA', models.FloatField(max_length=10)),
                ('regen_se_120HPA', models.FloatField(max_length=10)),
                ('regen_se_144HPA', models.FloatField(max_length=10)),
                ('regen_log_se_UC', models.FloatField(max_length=10)),
                ('regen_log_se_0HPA', models.FloatField(max_length=10)),
                ('regen_log_se_2HPA', models.FloatField(max_length=10)),
                ('regen_log_se_4HPA', models.FloatField(max_length=10)),
                ('regen_log_se_8HPA', models.FloatField(max_length=10)),
                ('regen_log_se_12HPA', models.FloatField(max_length=10)),
                ('regen_log_se_16HPA', models.FloatField(max_length=10)),
                ('regen_log_se_20HPA', models.FloatField(max_length=10)),
                ('regen_log_se_24HPA', models.FloatField(max_length=10)),
                ('regen_log_se_36HPA', models.FloatField(max_length=10)),
                ('regen_log_se_48HPA', models.FloatField(max_length=10)),
                ('regen_log_se_60HPA', models.FloatField(max_length=10)),
                ('regen_log_se_72HPA', models.FloatField(max_length=10)),
                ('regen_log_se_96HPA', models.FloatField(max_length=10)),
                ('regen_log_se_120HPA', models.FloatField(max_length=10)),
                ('regen_log_se_144HPA', models.FloatField(max_length=10)),
            ],
        ),
    ]
