# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0008_standard_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='embryo_cpm',
            name='mean_120HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='embryo_cpm',
            name='mean_12HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='embryo_cpm',
            name='mean_24HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='embryo_cpm',
            name='mean_2HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='embryo_cpm',
            name='mean_7HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
