# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0009_auto_20170316_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='mfuzz_score',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='nve_eval',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='nve_hit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='other_nr_hits',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='top_nr_hit_eval',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='uniprot_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='uniprot_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_0HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_10HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_11HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_12HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_13HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_14HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_15HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_16HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_17HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_18HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_19HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_1HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_2HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_3HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_4HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_5HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_6HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_7HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_8HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='fischer_anc_9HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_120HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_12HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_240HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_24HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_2HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='helm_anc_7HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_120HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_144HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_168HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_192HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_24HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_48HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_72HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='embryo_cpm',
            name='warner_anc_96HPF',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fasta',
            name='fasta_sequence',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_0HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_120HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_12HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_144HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_16HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_20HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_24HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_2HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_36HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_48HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_4HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_60HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_72HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_8HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_96HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_UC',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_0HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_120HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_12HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_144HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_16HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_20HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_24HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_2HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_36HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_48HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_4HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_60HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_72HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_8HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_96HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_log_se_UC',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_0HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_120HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_12HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_144HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_16HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_20HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_24HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_2HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_36HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_48HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_4HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_60HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_72HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_8HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_96HPA',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard_error',
            name='regen_se_UC',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
