# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0011_auto_20170320_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mfuzz',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('modal_title', models.CharField(max_length=40)),
                ('cluster_image', models.CharField(max_length=20)),
                ('bp_plot_image', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_0HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_120HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_12HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_144HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_16HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_20HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_24HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_2HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_36HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_48HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_4HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_60HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_72HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_8HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_96HPA',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='regen_cpm',
            name='regen_anc_UC',
            field=models.FloatField(blank=True, max_length=17, null=True),
        ),
    ]
