# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0012_auto_20170328_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfuzz',
            name='bp_plot_image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mfuzz',
            name='cluster_image',
            field=models.CharField(max_length=50),
        ),
    ]
