# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0014_mfuzz_clust_nb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfuzz',
            name='clust_nb',
        ),
    ]
