# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_plotter', '0015_remove_mfuzz_clust_nb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfuzz',
            name='modal_title',
        ),
        migrations.AddField(
            model_name='mfuzz',
            name='mfuzz_cluster_nb',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
